#!/bin/sh

chunkc core::log_file /usr/local/var/log/chunkwm/log
chunkc core::log_level warn
chunkc core::plugin_dir /usr/local/opt/chunkwm/share/chunkwm/plugins
chunkc core::hotload 0

# tiling
chunkc set custom_bar_enabled            0
chunkc set custom_bar_all_monitors       0
chunkc set custom_bar_offset_top         22
chunkc set custom_bar_offset_bottom      0
chunkc set custom_bar_offset_left        0
chunkc set custom_bar_offset_right       0

chunkc set global_desktop_mode           bsp
chunkc set global_desktop_offset_top     0
chunkc set global_desktop_offset_bottom  0
chunkc set global_desktop_offset_left    0
chunkc set global_desktop_offset_right   0
chunkc set global_desktop_offset_gap     0

chunkc set desktop_padding_step_size     10.0
chunkc set desktop_gap_step_size         5.0

chunkc set bsp_spawn_left                1
chunkc set bsp_optimal_ratio             1.618
chunkc set bsp_split_mode                optimal
chunkc set bsp_split_ratio               0.5

chunkc set monitor_focus_cycle           1
chunkc set window_focus_cycle            monitor
chunkc set mouse_follows_focus           intrinsic
chunkc set window_float_next             0
chunkc set window_region_locked          1

chunkc set mouse_move_window             \"fn 1\"
chunkc set mouse_resize_window           \"fn 2\"
chunkc set mouse_motion_interval         35

# sa: (https://github.com/koekeishiya/chwm-sa)

chunkc set window_float_topmost          0
chunkc set window_fade_inactive          0
chunkc set window_fade_alpha             0.85
chunkc set window_fade_duration          0.25
chunkc set window_use_cgs_move           0

# border

chunkc set focused_border_color          0x586e75
chunkc set focused_border_width          5
chunkc set preselect_border_color        0x586e75
chunkc set preselect_border_width        5
chunkc set focused_border_radius         0
chunkc set focused_border_skip_floating  0
chunkc set focused_border_skip_monocle   0

# load plugins

chunkc core::load border.so
chunkc core::load tiling.so

# tiling rules

#chunkc tiling::rule --owner Finder --name Copy --state float &
#chunkc tiling::rule --owner \"App Store\" --state float &
#chunkc tiling::rule --owner Safari --state float &
#chunkc tiling::rule --owner "Google Chrome" --state float &
chunkc tiling::rule --owner Emacs --except "^$" --state tile &
chunkc tiling::rule --owner Rune --state tile &
